name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Change this to the name of your main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.x'
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: gulp build # Change this to the command that builds your site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: kmp.andrefb.tech
          
